# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1aefa25b68a2c868114440b0595d46c396b67c8b7987ae22f6996d1e49ffbf5c8ae3478d85fafe0a80cb7a7feabe47a7aae13c5a0ed3cb8caad369e7000c23a8

test:
  secret_key_base: 06d0bf56d347f9ec96b04e26d982be5cc2314b8dd987762da1ec7ab0e20962ec9a231b0a53b529cc8f4f133e8a22abf73999d0df08573181883f429652fd4c1f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
